name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: tamctec/workflows/.github/workflows/publish.yml@main
    with:
      files: sense-node-c3-template.yaml
      name: Sense Node C3 Template